# Generated by Django 2.1.7 on 2019-03-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='회사명')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('comp_part', models.CharField(max_length=50, verbose_name='부서')),
                ('position', models.CharField(max_length=25, verbose_name='직위')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('phone', models.CharField(max_length=25, verbose_name='핸드폰 번호')),
                ('comp_number', models.CharField(max_length=25, verbose_name='사무실 번호')),
                ('fax_number', models.CharField(max_length=25, verbose_name='Fax 번호')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('remark', models.TextField(verbose_name='설명')),
            ],
        ),
    ]
