# Generated by Django 2.1.7 on 2019-03-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseKeepingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(blank=True, max_length=200, verbose_name='내용')),
                ('income', models.IntegerField(default=0, null=True, verbose_name='수입')),
                ('expense', models.IntegerField(default=0, null=True, verbose_name='지출')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='개수')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
